server:
    port: 10002

spring:
    kafka:
        bootstrap-servers: localhost:9092

        consumer:
            group-id: pg-gateway-group
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            isolation-level: read_committed
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
            transaction-id-prefix: pggw-tx-
            acks: all
            retries: 3
            enable-idempotence: true
        listener:
            ack-mode: record

logging:
    level:
        root: INFO
        com.roopy: DEBUG
        org.apache.kafka.clients.producer: DEBUG